#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""Fail unless every linked, compiled-in or bundled component in THIRD-PARTY.md has its source in the release archive.

usage: check-corresponding-source.py ROOT SOURCE-ARCHIVE.tar.xz [ENGINE-BUILD-DIR]

The executable is conveyed as one combined GPL-3.0 work, so the source of everything statically linked into it is part
of its corresponding source, whatever that component's own licence says (an elected FTL or zlib arm removes nothing).
Every row of a THIRD-PARTY.md component table whose Status column says linked, compiled or bundled must therefore be
listed in COVERAGE below, with the archive directories that hold its source, or in EXEMPT with the reason it needs
none (the compiler's own runtime and C library and the import stubs generated from the toolchain's headers; the
release build binds their revisions to $VITASDK/version_info.txt). A row the script does not know, a row whose cells
do not match its table's header, and a row with no Status are failures: add the component's source to the archive
(vita/scripts/source-archive.py) and list it here.

With ENGINE-BUILD-DIR, the libraries on the link line of the built executable are read from ninja and each must
belong to a THIRD-PARTY.md row: a library that was linked but never documented fails the release.
"""
import re
import subprocess
import sys
import tarfile
from pathlib import Path

root, archive = Path(sys.argv[1]), Path(sys.argv[2])
build_dir = Path(sys.argv[3]) if len(sys.argv) > 3 else None

ENGINE = "the branch (the source is in this tree)"
# Row name (start of the Component cell) -> archive component directories under dependencies/ ("branch" = this tree).
COVERAGE = {
    "mkxp-z": ("branch",),
    "vitaGL": ("vitagl",),
    "vitaShaRK": ("vitashark",),
    "SceShaccCgExt": ("shacccgext",),
    "math-neon": ("mathneon",),
    "taiHEN": ("taihen",),
    "SDL2 (": ("sdl2",),
    "SDL vitaGL video backend": ("sdl2",),
    "SDL2_image, SDL2_ttf": ("sdl2_image", "sdl2_ttf"),
    "libpng": ("libpng",),
    "zlib": ("zlib",),
    "bzip2": ("bzip2",),
    "libwebp": ("libwebp",),
    "FreeType": ("freetype",),
    "pixman": ("pixman",),
    "PhysFS": ("physfs",),
    "OpenAL Soft": ("openal-soft",),
    "SDL_sound": ("sdl_sound",),
    "libogg, libvorbis": ("libogg", "libvorbis"),
    "libtheora": ("libtheora",),
    "theoraplay": ("branch",),
    "TinySoundFont": ("tinysoundfont",),
    "uchardet": ("uchardet",),
    "Ruby": ("ruby",),
    "pthread-embedded": ("pthread-embedded",),
    "ghc::filesystem": ("branch",),
    "libnsgif": ("branch",),
    "rapidcsv": ("branch",),
    "sigslot": ("branch",),
    "json5pp": ("branch",),
}
# The vitasdk/packages recipes are the source of the vdpm binaries' build; any of these rows needs them.
VDPM_ROWS = {"libpng", "zlib", "bzip2", "libwebp", "FreeType", "PhysFS", "libogg, libvorbis", "SDL2_image, SDL2_ttf"}
EXEMPT = {
    "VitaSDK newlib": "the C and maths library of the VitaSDK compiler package: a System Library of the compiler, "
                      "permissively licensed; its revision is bound to $VITASDK/version_info.txt at release time",
    "libstdc++, libgcc": "GPL-3.0 with the GCC Runtime Library Exception: a program compiled with GCC (with or "
                         "without modifications) and linked with them may be conveyed under any licence, and they are "
                         "the compiler's own runtime",
    "vita-headers import stubs": "import stubs generated by the VitaSDK tools from the pinned vita-headers (MIT); "
                                 "the headers' revision is bound to the pin through $VITASDK/version_info.txt at "
                                 "release time",
}
FONTS = ("fonts",)
STATUS = re.compile(r"linked|compiled|bundled")

# Libraries on the link line -> the row (key of COVERAGE or EXEMPT) that accounts for them.
LIBRARIES = {
    "libopenal.a": "OpenAL Soft", "libz.a": "zlib", "libbz2.a": "bzip2", "libSDL2.a": "SDL2 (",
    "libvitaGL.a": "vitaGL", "libvitashark.a": "vitaShaRK", "libmathneon.a": "math-neon",
    "libSceShaccCgExt.a": "SceShaccCgExt", "libtaihen_stub.a": "taiHEN", "libSDL2_sound.a": "SDL_sound",
    "libpixman-1.a": "pixman", "libphysfs.a": "PhysFS", "libtheora.a": "libtheora", "libogg.a": "libogg, libvorbis",
    "libvorbis.a": "libogg, libvorbis", "libvorbisfile.a": "libogg, libvorbis", "libSDL2_ttf.a": "SDL2_image, SDL2_ttf",
    "libSDL2_image.a": "SDL2_image, SDL2_ttf", "libfreetype.a": "FreeType", "libpng16.a": "libpng",
    "libpng.a": "libpng", "libwebp.a": "libwebp", "libwebpdemux.a": "libwebp", "libsharpyuv.a": "libwebp",
    "libuchardet.a": "uchardet", "libruby-static.a": "Ruby", "libstdc++.a": "libstdc++, libgcc",
    "libgcc.a": "libstdc++, libgcc", "libm.a": "VitaSDK newlib", "libc.a": "VitaSDK newlib",
    "libpthread.a": "pthread-embedded",
}
IMPORT_STUB = re.compile(r"libSce[A-Za-z0-9]+_stub(_weak)?\.a")


def die(message):
    sys.exit("check-corresponding-source: " + message)


def cells(line):
    return [cell.strip() for cell in line.strip().strip("|").split("|")]


def key_of(name):
    """The longest COVERAGE or EXEMPT key that starts the component name, else None."""
    matches = [k for k in list(COVERAGE) + list(EXEMPT) if name.startswith(k)]
    return max(matches, key=len) if matches else None


rows = []
font_rows = 0
header = None
for number, line in enumerate((root / "THIRD-PARTY.md").read_text(encoding="utf-8").splitlines(), 1):
    if not line.startswith("|"):
        header = None
        continue
    fields = cells(line)
    if header is None:
        header = fields
        if header[0] not in ("Component", "File"):
            die("THIRD-PARTY.md:%d: a table headed %r is neither a component nor a font table" % (number, header[0]))
        continue
    if set(line) <= set("|- :"):
        continue
    if len(fields) != len(header):
        die("THIRD-PARTY.md:%d: row has %d cells, its table header %d: %s" % (number, len(fields), len(header), line[:80]))
    if header[0] == "File":
        font_rows += 1
        continue
    if header[:1] + header[4:5] != ["Component", "Status"]:
        die("THIRD-PARTY.md:%d: component table has no Status column (%s)" % (number, ", ".join(header)))
    row = dict(zip(header, fields))
    if not row["Component"] or not STATUS.search(row["Status"]):
        die("THIRD-PARTY.md:%d: %r has no linked, compiled or bundled Status (%r)" % (number, row["Component"], row["Status"]))
    rows.append(row)
if not rows:
    die("no component rows found in THIRD-PARTY.md")

wanted = {}
exempt = set()
keys = set()
for row in rows:
    name = row["Component"].replace("`", "")
    key = key_of(name)
    if key is None:
        die("%r is %s, but has no source in the release archive and no exemption (add it to check-corresponding-source.py)"
            % (name, row["Status"]))
    keys.add(key)
    if key in EXEMPT:
        exempt.add(key)
    else:
        wanted[key] = COVERAGE[key]
if font_rows:
    wanted["Fonts"] = FONTS
if keys & VDPM_ROWS:
    wanted["vdpm recipes"] = ("vitasdk-packages",)

counts = {}
with tarfile.open(archive, "r:xz") as tar:
    for member in tar:
        if not member.isfile():
            continue
        parts = member.name.split("/")
        if len(parts) > 2 and parts[1] == "branch":
            counts["branch"] = counts.get("branch", 0) + 1
        elif len(parts) > 3 and parts[1] == "dependencies":
            counts[parts[2]] = counts.get(parts[2], 0) + 1
missing = sorted("%s (%s)" % (key, folder) for key, folders in wanted.items() for folder in folders if not counts.get(folder))
if missing:
    die("the archive holds no source for: %s" % ", ".join(missing))

if build_dir is not None:
    try:
        lines = subprocess.run(["ninja", "-C", str(build_dir), "-t", "commands", "mkxp-z.cortex-a9"], check=True,
                               capture_output=True, text=True).stdout.splitlines()
    except (OSError, subprocess.CalledProcessError) as error:
        die("cannot read the link line from %s: %s" % (build_dir, error))
    tokens = lines[-1].split() if lines else []
    if "-o" not in tokens:
        die("the last ninja command for the executable is not a link line")
    linked = set()
    # Build-local archives are part of this tree, not an external component.
    own = [Path(token[2:]) for token in tokens if token.startswith("-L") and build_dir.resolve() in Path(token[2:]).resolve().parents]
    for token in tokens:
        if token.startswith("-l"):
            name = "lib%s.a" % token[2:]
            if not any((directory / name).is_file() for directory in own):
                linked.add(name)
        elif token.endswith(".a"):
            path = Path(token)
            if not (path.is_absolute() and build_dir.resolve() in path.resolve().parents):
                linked.add(path.name)
    unknown = sorted(name for name in linked if name not in LIBRARIES and not IMPORT_STUB.fullmatch(name))
    if unknown:
        die("the executable links %s, which THIRD-PARTY.md does not account for (add the library to check-corresponding-source.py)"
            % ", ".join(unknown))
    unlisted = sorted({LIBRARIES[name] for name in linked if name in LIBRARIES} - keys)
    if any(IMPORT_STUB.fullmatch(name) for name in linked) and "vita-headers import stubs" not in keys:
        unlisted.append("vita-headers import stubs")
    if unlisted:
        die("the executable links libraries of %s, which THIRD-PARTY.md has no row for" % ", ".join(sorted(unlisted)))
    print("check-corresponding-source: the link line holds %d libraries, all accounted for" % len(linked))

print("check-corresponding-source: %d components with source in the archive (%s); exempt: %s" % (
    len(wanted), ", ".join(sorted(key.rstrip(" (") for key in wanted)), ", ".join(sorted(exempt))))
